"""init

Revision ID: 83b06df270ec
Revises: 
Create Date: 2025-12-22 02:36:23.222840

"""
from alembic import op
import sqlalchemy as sa



revision = '83b06df270ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
