export const MINOR_MODES = {
  dorian: {
    name: 'Dorian',
    keywords: ['dorian', 'jazzy', 'soulful', 'funky', 'minor hopeful', 'smooth'],
    description: 'Minor with a hopeful edge - jazz and soul favorite',
    chordType: 'm7',
    formula: '1 - 2 - b3 - 4 - 5 - 6 - b7',
    characteristics: [
      'Minor tonality with a raised 6th creates hopefulness',
      'Sophisticated, jazzy feel - less dark than natural minor',
      'Perfect for introspective but not sad music',
      'Used extensively in jazz, funk, and film scores',
      'Hans Zimmer\'s "Time" (Inception) uses Dorian',
    ],
    progressions: ['i - IV', 'i7 - IV7', 'i - ii - bVII - IV'],
    keyExamples: 'D Dorian = D-E-F-G-A-B-C, A Dorian = A-B-C-D-E-F#-G',
    bestInstruments: ['Rhodes', 'electric piano', 'bass', 'jazz brushes', 'saxophone'],
  },
  aeolian: {
    name: 'Aeolian (Natural Minor)',
    keywords: ['aeolian', 'natural minor', 'minor', 'sad', 'melancholic', 'emotional'],
    description: 'The classic minor scale - melancholic and dramatic',
    chordType: 'm7',
    formula: '1 - 2 - b3 - 4 - 5 - b6 - b7',
    characteristics: [
      'The most common minor sound in Western music',
      'Conveys sadness, drama, and emotional depth',
      'Perfect for ballads and dramatic moments',
      'Foundation for classical, rock, and pop minor keys',
      'Beethoven\'s "Moonlight Sonata" exemplifies this mode',
    ],
    progressions: ['i - bVI - bVII - i', 'i - iv - v', 'i - bVII - bVI - bVII'],
    keyExamples: 'A Aeolian = A-B-C-D-E-F-G, E Aeolian = E-F#-G-A-B-C-D',
    bestInstruments: ['strings', 'piano', 'cello', 'choir', 'violin'],
  },
  harmonic_minor: {
    name: 'Harmonic Minor',
    keywords: ['harmonic minor', 'classical', 'gothic', 'vampire', 'eastern european', 'dramatic tension'],
    description: 'Dramatic and exotic - classical tension with raised 7th',
    chordType: 'm(maj7)',
    formula: '1 - 2 - b3 - 4 - 5 - b6 - 7',
    characteristics: [
      'The raised 7th creates strong pull to tonic (leading tone)',
      'Augmented 2nd between b6 and 7 gives exotic, Eastern flavor',
      'The "vampire" or "gothic" sound in film scores',
      'Essential for classical minor key harmony (V7 chord)',
      'Mozart, Tchaikovsky, and gothic film scores',
    ],
    progressions: ['i - V7', 'i - iv - V7 - i', 'i - bVI - V7'],
    keyExamples: 'A Harmonic Minor = A-B-C-D-E-F-G#, E Harmonic Minor = E-F#-G-A-B-C-D#',
    bestInstruments: ['strings', 'piano', 'harpsichord', 'organ', 'choir'],
  },
  melodic_minor: {
    name: 'Melodic Minor',
    keywords: ['melodic minor', 'jazz minor', 'sophisticated', 'noir', 'smooth jazz', 'film noir'],
    description: 'Sophisticated and jazzy - the "thinking person\'s minor"',
    chordType: 'm(maj7)',
    formula: '1 - 2 - b3 - 4 - 5 - 6 - 7',
    characteristics: [
      'Raised 6th and 7th smooth out the augmented 2nd',
      'Foundation of jazz harmony - generates altered dominants',
      'Film noir, sophisticated, introspective quality',
      'Less exotic than harmonic minor, more flowing',
      'Jazz standards and contemporary film scores',
    ],
    progressions: ['i(maj7)', 'i - ii - V7alt', 'i(maj7) - IV7'],
    keyExamples: 'A Melodic Minor = A-B-C-D-E-F#-G#, C Melodic Minor = C-D-Eb-F-G-A-B',
    bestInstruments: ['piano', 'upright bass', 'saxophone', 'muted trumpet', 'vibraphone'],
  },
  phrygian: {
    name: 'Phrygian',
    keywords: ['phrygian', 'spanish', 'flamenco', 'exotic', 'middle eastern', 'tense', 'metal'],
    description: 'Exotic and tense - Spanish flamenco and metal favorite',
    chordType: 'm7',
    formula: '1 - b2 - b3 - 4 - 5 - b6 - b7',
    characteristics: [
      'The b2 creates immediate exotic tension',
      'Evokes Spanish flamenco and Middle Eastern sounds',
      'Common in metal for dark, aggressive riffs',
      'Creates a sense of danger and intensity',
      'Perfect for dramatic, confrontational moments',
    ],
    progressions: ['i - bII', 'i - bII - bVII - i', 'i - bII - i'],
    keyExamples: 'E Phrygian = E-F-G-A-B-C-D, A Phrygian = A-Bb-C-D-E-F-G',
    bestInstruments: ['acoustic guitar', 'flamenco guitar', 'percussion', 'brass', 'strings'],
  },
  locrian: {
    name: 'Locrian',
    keywords: ['locrian', 'dissonant', 'unstable', 'experimental', 'horror'],
    description: 'The darkest, most unstable mode - for experimental and horror',
    chordType: 'm7b5',
    formula: '1 - b2 - b3 - 4 - b5 - b6 - b7',
    characteristics: [
      'The diminished 5th makes it highly unstable',
      'Rarely used as a tonal center due to dissonance',
      'Perfect for horror, tension, and experimental music',
      'Creates a sense of unease and dread',
      'Use sparingly for maximum effect',
    ],
    progressions: ['i° - bII', 'Avoid prolonged use - works best as passing color'],
    keyExamples: 'B Locrian = B-C-D-E-F-G-A',
    bestInstruments: ['distorted synth', 'strings', 'prepared piano', 'percussion', 'bass'],
  },
} as const;

export type MinorMode = keyof typeof MINOR_MODES;
